import type { Event, User, LeaderboardEntry } from './types';

export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'Alice',
    email: 'alice@example.com',
    role: 'citizen',
    country: 'it',
    ecoPoints: 1250,
    badges: ['RecyclingHero', 'TreePlanter'],
    profileImage: 'https://picsum.photos/seed/user1/100/100',
    contributions: 'Organized 3 recycling drives and planted 20 trees.',
  },
  {
    id: 'user2',
    name: 'Bob',
    email: 'bob@example.com',
    role: 'citizen',
    country: 'nl',
    ecoPoints: 800,
    badges: ['CleanupCrew'],
    profileImage: 'https://picsum.photos/seed/user2/100/100',
    contributions: 'Participated in 5 beach cleanups.',
  },
];

export const mockEvents: Event[] = [
  {
    id: 'event1',
    title: 'Milan Park Cleanup',
    description: 'Join us for a community cleanup at Parco Sempione.',
    category: 'cleanup',
    location: { latitude: 45.4722, longitude: 9.1772 },
    address: 'Piazza Sempione, 20154 Milano MI, Italy',
    country: 'it',
    date: new Date('2024-08-15T09:00:00'),
    createdBy: 'Green Milan',
    participants: ['Alice', 'Marco'],
    impact: { plasticCollectedKg: 50 },
    beforePhotos: ['https://picsum.photos/seed/event1before/400/300'],
    afterPhotos: ['https://picsum.photos/seed/event1after/400/300'],
  },
  {
    id: 'event2',
    title: 'Amsterdam Canal Gardening',
    description: 'Planting flowers along the canals to beautify the city.',
    category: 'gardening',
    location: { latitude: 52.379189, longitude: 4.899431 },
    address: 'Amsterdam, Netherlands',
    country: 'nl',
    date: new Date('2024-08-20T10:00:00'),
    createdBy: 'Amsterdam Blooms',
    participants: ['Bob', 'Chris'],
    impact: { treesPlanted: 150 },
    beforePhotos: ['https://picsum.photos/seed/event2before/400/300'],
    afterPhotos: ['https://picsum.photos/seed/event2after/400/300'],
  },
  {
    id: 'event3',
    title: 'Stockholm Recycling Workshop',
    description: 'A workshop on advanced recycling techniques and waste reduction.',
    category: 'recycling',
    location: { latitude: 59.3293, longitude: 18.0686 },
    address: 'Stockholm, Sweden',
    country: 'se',
    date: new Date('2024-09-01T14:00:00'),
    createdBy: 'Recycle SE',
    participants: [],
    impact: {},
    beforePhotos: ['https://picsum.photos/seed/event3before/400/300'],
    afterPhotos: [],
  },
  {
    id: 'event4',
    title: 'Beirut Coastal Cleanup',
    description: 'A large-scale cleanup operation along the coast of Beirut.',
    category: 'cleanup',
    location: { latitude: 33.8938, longitude: 35.5018 },
    address: 'Beirut, Lebanon',
    country: 'lb',
    date: new Date('2024-09-05T08:00:00'),
    createdBy: 'Lebanon Ocean Guard',
    participants: [],
    impact: { plasticCollectedKg: 200 },
    beforePhotos: ['https://picsum.photos/seed/event4before/400/300'],
    afterPhotos: [],
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
    { rank: 1, user: { name: 'Elena Rossi', profileImage: 'https://picsum.photos/seed/lb1/40/40', country: 'it' }, ecoPoints: 2300 },
    { rank: 2, user: { name: 'Lars Andersen', profileImage: 'https://picsum.photos/seed/lb2/40/40', country: 'se' }, ecoPoints: 2150 },
    { rank: 3, user: { name: 'Fatima Al-Sayed', profileImage: 'https://picsum.photos/seed/lb3/40/40', country: 'lb' }, ecoPoints: 1980 },
    { rank: 4, user: { name: 'Sven van der Berg', profileImage: 'https://picsum.photos/seed/lb4/40/40', country: 'nl' }, ecoPoints: 1800 },
    { rank: 5, user: { name: 'Youssef Hamidi', profileImage: 'https://picsum.photos/seed/lb5/40/40', country: 'ma' }, ecoPoints: 1750 },
    { rank: 6, user: { name: 'Amira Bouazizi', profileImage: 'https://picsum.photos/seed/lb6/40/40', country: 'tn' }, ecoPoints: 1600 },
];
